import Head from "next/head";
import Image from "next/image";
import Countries from "../components/seccion/Countries";
import Header from "../components/Header";
import { getCountryAll } from "../service/Axios";

export default function Home({ countries }) {
  return (
    <div>
      <Head>
        <title>Country Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Countries countries={countries} />
    </div>
  );
}

// export const getServerSideProps = async () => {
//   try {
//     const respose = await getCountryAll();
//     const data = respose.data;

//     return {
//       props: { countries: data },
//     };
//   } catch {
//     return {
//       props: { error: true },
//     };
//   }
// };

export const getStaticProps = async () => {
  const respose = await getCountryAll();

  return {
    props: { countries: respose.data },
  };
};
